kumuluzee:
  name: rso-trackMetadata
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/TrackMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/track_metadata
      username: postgres
      password:
      max-pool-size: 20
rest-properties:
  external-services:
    order-service:
      enabled: true
